### ISSUE TITLE
Remove TTS & translations

### ISSUE THREAD

**Issue by mat-1** [mat-1/Repldex#64]
In my opinion these features just add clutter and are completely unnecessary, not to mention the fact that they don't even work. Please reply to this issue if you agree or disagree

**Comment by jetstream0** [comment]
I agree with removing both, mostly because I don't want to fix translations anymore.
We should focus on more useful features like https://github.com/mat-1/Repldex/issues/14
We can leave those in a legacy branch or something so we don't lose the code in case someone feels like reviving them in the future.

**Comment by Codemonkey51** [comment]
> We can leave those in a legacy branch or something so we don't lose the code in case someone feels like reviving them in the future.

or just have it in a git tag /release

**Comment by jetstream0** [comment]
sure

**Comment by jetstream0** [comment]
well we're at it we can remove broken deletions from master

**Comment by leon332157** [comment]
Removed in #69
